language: python
sudo: false
branches:
  only:
    - master
python:
  - 3.6
  - 3.7
  - 3.8
  - "pypy3"
install:
  - pip install -e .
  - pip install coveralls
script:
  - coverage run --source=jsx setup.py test
after_success:
  - coveralls
